config/routes.rb
Helpme::Application.routes.draw do
  get "site/index"
  devise_for :users, :controllers => { :registrations => :registrations }

  resources :users, :only => [:show]
  resources :posts do
    member do
      put :cover
    end
    resources :images, :only => [:create, :destroy]
  end
  root :to => 'site#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(current_user)
    current_user ||= User.new # guest user
    can :read, :all
    can :update, User do |user|
      user == current_user
    end

    can :update, Post do |post|
      post.try(:user) == current_user
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post
  mount_uploader :url, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :cover, :class_name => 'Image', :foreign_key => 'cover_id'
  has_many :images, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings

  scope :recent, order('created_at DESC')
  scope :tagged, lambda { |tag_id| tag_id ? joins(:taggings).where(:taggings => {:tag_id => tag_id}) : scoped }

  validates_presence_of :title, :content
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i, :allow_blank => true

  def tag_names=(names)
    self.tags = Tag.with_names(names.strip.split(/,+/).map{ |n| n.strip }.uniq)
  end

  def tag_names
    tags.map(&:name).join(', ')
  end

  def self.primitive_search(fields, query)
    where(primitive_search_conditions(fields, query))
  end

  def self.primitive_search_conditions(fields, query)
    query.split(/\s+/).map do |word|
      '(' + fields.map { |col| "#{col} LIKE #{sanitize('%' + word.to_s + '%')}" }.join(' OR ') + ')'
    end.join(" AND ")
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  mount_uploader :avatar, ImageUploader
  belongs_to :user
  validates_length_of :description, :maximum => 500

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, :dependent => :destroy
  has_many :posts, :through => :taggings

  def self.with_names(names)
    names.map do |name|
      Tag.find_or_create_by_name(name.strip)
    end
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable,:omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_many :posts
  has_one :profile
  accepts_nested_attributes_for :profile
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_attributes

  validates_presence_of :first_name, :last_name
  after_create :create_profile



  def full_name
    self.first_name + ' ' + self.last_name
  end

  private

  def create_profile
    self.create_profile!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :destroy ]
  before_filter :set_post_and_image

  def create
    respond_to do |format|
      unless @image.save
        flash[:error] = t('Photo could not be uploaded')
      end
      format.js do
        render :text => render_to_string(:partial => 'images/image', :locals => {:image => @image})
      end
    end
  end

  def destroy
    respond_to do |format|
      unless @image.destroy
        flash[:error] = t('Photo could not be deleted')
      end
      format.js
    end
  end

  private

  def set_post_and_image
    @post = current_user.posts.find(params[:post_id])
    raise ActiveRecord::RecordNotFound unless @post
    @image = params[:id] ? @post.images.find(params[:id]) : @post.images.build(params[:image])
  end
end

app/controllers/posts_controller.rb
#-*- coding: utf-8 -*-
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  load_resource

  respond_to :html, :json, :js
  def index
    @posts = Post.recent.includes(:cover, :tags).page(params[:page]).per_page(20)
    prepare_search
    respond_with @posts
  end

  def show
    @post = Post.find params[:id]
  end

  def new
    @post = Post.new
    respond_with @post
  end

  def edit
    @post = current_user.posts.find params[:id]
  end

  def create
    @post = current_user.posts.build params[:post]

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Запись успешно создана.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Запись успешно отредактирована.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end

  def cover
    @post = current_user.posts.find params[:id]
    @post.cover = @post.images.find params[:image_id]
    @post.save :validate => false
    respond_to do |format|
      format.js
    end
  end

  private

  def prepare_search
    if params[:q].present?
      @posts = @posts.primitive_search %w[title content], params[:q]
    end
    if params[:location].present?
      @posts = @posts.primitive_search %w[location], params[:location]
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected
  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @posts = Post.recent.limit(3)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_resource
  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title) { page_title.to_s }
  end

  def page_title (page_title)
    content_for(:page_title) { page_title.to_s }
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end

  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end

  def nav_link(link_text, link_path, active = false)
    class_name = active ? 'active' : ''
    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end

  def nl2br(string)
    string.gsub /\n\s*/, '<br>'
  end

  def error_message(key, object = nil)
    object = resource if object.nil?
    content_tag :span, object.errors.messages[key][0], :class => 'help-inline' if error_exists?(key, object)
  end

  def error_exists?(key, object = nil)
    object = resource if object.nil?
    object.errors.any? && object.errors.messages.key?(key)
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def cover(post, size = '50x50')
    image_tag cover_url(post), :alt => post.title, :size => size
  end

  def cover_url(post)
    if post.cover and post.cover.url.present?
      post.cover.url_url(:profile_avatar)
    else
      '/assets/default_avatar_150.png'
    end
  end

  def view_tags(post)
    post.tags.map{ |tag| link_to tag.name, posts_path(:tag_id => tag.id ) }.join(', ')
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar(user, size = '50x50')
    if user.profile.avatar.present?
      image_tag user.profile.avatar_url(:profile_avatar), :alt => user.full_name, :size => size
    else
      image_tag '/assets/default_avatar_150.png', :alt => user.full_name, :size => size
    end
  end
end

app/views/images/_image.html.erb
<li class="span2" id="<%= dom_id(image) %>">
  <div class="photo thumbnail">
    <%= image_tag image.url_url(:thumb) if image.url? %>
    <div class="caption">
      <%= link_to 'Удалить', post_image_path(@post, image), :method => :delete, :confirm => "Вы уверены?", :remote => :true %>
      <%= link_to 'Обложка', cover_post_path(@post, :image_id => image.id), :method => :put, :remote => :true, :class => 'set_cover', :style => @post.cover == image ? 'display:none' : '' %>
    </div>
  </div>
</li>

app/views/images/destroy.js.erb
<% if flash[:error].blank? %>
  $('#image_<%= @image.id %>').remove();
<% end %>

app/views/layouts/_user_menu.html.erb
<ul class="nav pull-right">
<% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=h current_user.full_name %><b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Профиль', user_path(current_user) %></li>
      <li><a href="#">Сообщения</a></li>
      <li class="divider"></li>
      <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
    </ul>
  </li>
  <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
<% else %>
  <li><%= link_to 'Войти', new_user_session_path %></li>
  <li class="divider-vertical"></li>
  <li><%= link_to 'Регистрация', new_user_registration_path %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title><%= h(yield(:title) || 'Помоги ближнему!') %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="maxlapko">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/assets/favicon.ico">
    <link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/assets/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/assets/apple-touch-icon-114x114.png">
    <% if content_for?(:scripts) %>
      <%= yield(:scripts) %>
    <% end %>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'Помоги ближнему', root_path, :class => 'brand' %>
          <div class="nav-collapse">
            <ul class="nav">
              <%= nav_link 'Проблемы', posts_path, controller?('posts') %>
              <%= nav_link 'Контакты', '#', false %>
            </ul>
            <%= render 'layouts/user_menu' %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div id="container" class="container">
      <% flash.each do |key, msg| %>
        <%= content_tag :div, :class => "alert alert-#{(key == :notice) ? 'success' : 'error'}" do %>
          <a class="close" data-dismiss="alert">&times;</a>
          <%=h msg %>
        <% end %>
      <% end %>
      <div class="row">
        <div class="span12">
          <%= yield %>
        </div>
      </div>
      <hr>
      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :class => 'form-horizontal' do |f| %>
  <fieldset>
    <legend><%= @post.new_record? ? 'Создание' : 'Редактирование'%> проблемы</legend>
    <div class="control-group<%= error_exists?(:title, @post) ? ' error' : '' %>">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'input-xlarge' %>
        <%= error_message :title, @post %>
      </div>
    </div>
    <div class="control-group<%= error_exists?(:content, @post) ? ' error' : '' %>">
      <%= f.label :content, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :content, :class => 'input-xxlarge', :size => '20x10' %>
        <%= error_message :content, @post %>
      </div>
    </div>
    <div class="control-group<%= error_exists?(:email, @post) ? ' error' : '' %>">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'input-xlarge' %>
        <%= error_message :email, @post %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :tag_names, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :tag_names, :class => 'input-xlarge' %>
        <p class="help-block">Разделяйте теги запятой.</p>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :location, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :location, :class => 'input-xlarge' %>
        <p class="help-block">Страна, город, населённый пункт.</p>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit @post.new_record? ? 'Создать' : 'Сохранить', :class => 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/posts/_post.html.erb
<a class="small_post" href="<%= post_path(post) %>">
  <div class="post_cover">
    <%= cover(post) %>
  </div>
  <div class="post_content">
    <div class="post_title">
      <h4><%=h post.title %></h4>
    </div>
    <div class="post_tags">
      <h4>
        <small>
          <%= Russian::strftime(post.created_at, '%d %b в %H:%M')%>
          <span> | </span>
          <%=h post.tag_names %>
        </small>
      </h4>
    </div>
  </div>
  <div class="post_location">
    <i class="icon-flag"></i>
    <%=h post.location %>
  </div>
</a>

app/views/posts/_post_template.html.erb
<a class="small_post" href="{{url}}">
  <div class="post_cover">
    <img src="{{cover_url}}" alt="{{title}}" width="50" height="50"/>
  </div>
  <div class="post_content">
    <div class="post_title">
      <h4>{{title}}</h4>
    </div>
    <div class="post_tags">
      <h4>
        <small>
          {{created_at}}
          <span> | </span>
          {{tag_names}}
        </small>
      </h4>
    </div>
  </div>
  <div class="post_location">
    <i class="icon-flag"></i>
    {{location}}
  </div>
</a>

app/views/posts/cover.js.erb
$('#images a.set_cover').show();
$('#image_<%= @post.cover.id %> a.set_cover').hide();

app/views/posts/edit.html.erb
<% title 'Редактирование проблемы' %>
<%- key = Rails.application.config.session_options[:key] %>
<%= content_for :scripts do %>
<script>
  $(function() {
    var upload_params = {
      '<%= key %>' : '<%= cookies[key] %>',
      '<%= request_forgery_protection_token %>' : '<%= form_authenticity_token %>',
      '_http_accept': 'application/javascript'
    };
    var url = $('#image_url').data('url');
    console.log(url);
    $('#image_url').uploadify({
      swf          : '/assets/uploadify.swf',
      uploader     : url,
      fileObjName  : 'image[url]',
      checkExisting: false,
      buttonText   : 'Загрузить изображения',
      cancelImage  : '/assets/cancel.png',
      multi        : true,
      postData     : upload_params,
      auto         : true,
      fileTypeDesc : 'All Image Files',
      fileTypeExts : '*.png;*.jpg;*.jpeg;*.gif',
      width        : 150,
      onUploadSuccess : function(e, response, data) {
        $('#images').append(response);
      }
    });
  });
</script>
<% end %>

<div class="tabbable" style="margin-bottom: 9px;">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#general_tab" data-toggle="tab">Общая информация</a></li>
    <li class=""><a href="#images_tab" data-toggle="tab">Изображения</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="general_tab">
      <%= render 'form' %>
    </div>
    <div class="tab-pane" id="images_tab">
      <div id="image_uploader">
        <%= fields_for Image.new do |f| %>
          <%= f.file_field :url, :data => { :url => post_images_path(@post) } %>
        <% end %>
      </div>
      <ul id="images" class="thumbnails"><%= render :partial => 'images/image', :collection => @post.images %></ul>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'shared/search' %>
<div class="row">
  <div class="span9">
    <div id="posts">
      <%= render @posts %>
    </div>
  </div>
  <div class="span3">

  </div>
</div>
<script type="text/template" id="post_template">
  <%= render 'posts/post_template' %>
</script>

app/views/posts/new.html.erb
<% title 'Создание проблемы' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= content_for :scripts do %>
  <%= stylesheet_link_tag 'jqGallery' %>
  <%= javascript_include_tag 'jqGallery' %>
  <script>
    $(function() {
      if ($('#gallery li').length > 0) {
        $('#gallery').jqGalViewII();
      }
    });
  </script>
<% end %>
<% title @post.title %>
<div class="row">
  <div class="span9">
    <div class="post">
      <div class="post_head">
        <% if @post.email.present? %>
          <div class="pull-right"><%= mail_to @post.email, 'Помочь', :class => 'btn btn-large btn-success' %></div>
        <% end %>
        <h2><%=h @post.title %></h2>
        <h4>
          <small>
            <%= Russian::strftime(@post.created_at, '%d %b в %H:%M')%>
            <span> | </span>
            <i class="icon-flag"></i>
            <%= @post.location %>
            <span> | </span>
            <%=raw view_tags(@post) %>
          </small>
        </h4>
      </div>
      <p class="post_content">
        <%= image_tag @post.cover.url_url(:thumb), :class => 'cover_img' unless @post.cover_id.nil? %>
        <%=raw nl2br(h @post.content) %>
      </p>
      <div class="post_footer">
        <ul id="gallery">
          <% @post.images.each do |image| %>
            <li><a href="<%= image.url_url %>" title="<%= image.title %>"><%= image_tag image.url_url(:small), :alt => image.title, :border => '0' %></a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="span3">
    <div class="post_avatar_block thumbnail clearfix">
      <div class="image_block">
        <a href="<%= user_path(@post.user) %>" title="<%= @post.user.full_name %>"><%= avatar(@post.user) %></a>
      </div>
      <div class="desc_block"><strong><%=h @post.user.full_name %></strong></div>
    </div>

    <% if can? :update, @post %>
      <h4>Управление</h4>
      <ul class="nav nav-pills nav-stacked">
        <li><a href="<%= edit_post_path(@post) %>" title="Редактировать">Редактировать</a></li>
      </ul>
    <% end %>
  </div>

</div>

app/views/shared/_search.html.erb
<div class="well" id="search">
  <form class="form-horizontal" action="<%= posts_path(:format => :json) %>" method="get" id="search_form">
    <div class="section">
      <div class="input-prepend">
        <span class="add-on"><i class="icon-user"></i></span>
        <input type="text" placeholder="Ключевое слово" class="input-xlarge" name="q" id="q" />
      </div>
    </div>
    <div class="section">
      <div class="input-prepend">
        <span class="add-on"><i class="icon-flag"></i></span>
        <input type="text" placeholder="Местоположение" class="input-xlarge" name="location" id="location" />
      </div>
    </div>
  </form>
  <div class="right-section"><%= link_to 'Есть проблема', new_post_path, :class => 'btn btn-large btn-danger' %></div>
</div>

app/views/site/index.html.erb
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
  <h1>Hello, world!</h1>
  <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
  <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
  <% @posts.each do |post| %>
    <div class="span4">
      <h2><%=h post.title %></h2>
      <p>
        <%= image_tag post.cover.url_url(:thumb), :class => 'cover_img', :width => 100 unless post.cover_id.nil? %>
        <%=raw nl2br(h truncate(post.content, :length => 300)) %>
      </p>
      <p><%= link_to 'Детально >>', post_path(post), :class => 'btn' %></p>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% title "Профиль #{@user.full_name}" %>
<div id="profile" class="thumbnail">
  <div class="avatar">
    <%= avatar(@user, '100x100') %>
  </div>
  <div class="content">
    <h2>
      <%= @user.full_name %>
      <% if can? :update, @user %>
        <div class="manage-section">
          <%= link_to 'Редактировать', edit_user_registration_path, :class => 'btn' %>
        </div>
      <% end %>
    </h2>
    <dl>
      <dt>О себе</dt>
      <dd><%=h @user.profile.description %></dd>
      <dt>Местоположение</dt>
      <dd><%=h @user.profile.location %></dd>
    </dl>
  </div>
</div>
<h3>Опубликованные проблемы</h3>
<div id="posts">
  <%= render @user.posts %>
</div>